version: '3'
services:
  database:
    image: postgres:11.0
    restart: always
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/jacob-project/backend:master
    restart: always
    env_file:
      - prod.env
    ports:
      - "9000:8000"
    depends_on:
      - database
    command: 'sh /scripts/run.sh'
    volumes:
      - static-files:/static-files
      - media-files:/media-files

volumes:
  database:
  media-files:
    external: true
  static-files:
    external: true

networks:
  default:
    external:
      name: jacob
