version: '3'
services:
  nginx:
      image: 'nginx:latest'
      volumes:
      - static-files:/static-files
      - media-files:/media-files
      - ./config:/etc/nginx/conf.d
      ports:
      - '80:80'
      - '443:443'
      command: /bin/bash -c "nginx -g 'daemon off;'"


  database:
    image: postgres:11.0
    restart: always
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-2018-09/personal-projects/jacob-project/backend:latest
    restart: always
    command: "/usr/sbin/sshd -D"
    env_file: dev.env
    ports:
      - "49279:22"
      - "8875:8000"
    volumes:
      - ./media-files:/media-files
      - ./static-files:/static-files
      - ./app:/app
      - ./scripts:/scripts
    depends_on:
      - database

volumes:
  database:
  static-files:
  media-files:
